"""Agregando nickname Usuario

Revision ID: 359cd5385dc1
Revises: 4c501f6ace3a
Create Date: 2024-01-17 19:26:05.284450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359cd5385dc1'
down_revision = '4c501f6ace3a'
branch_labels = None
depends_on = None

inspector=sa.inspect(op.get_bind())

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        if 'nickname' not in [c["name"] for c in inspector.get_columns('usuario')]:
            batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
            batch_op.create_unique_constraint('uq_usuario_nickname', ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        if 'nickname' in [c["name"] for c in inspector.get_columns('usuario')]:
            batch_op.drop_constraint('uq_usuario_nickname', type_='unique')
            batch_op.drop_column('nickname')

    # ### end Alembic commands ###
