"""Agregando a Tabla NotadePedido pagos, vuelto

Revision ID: 729af6d55beb
Revises: 359cd5385dc1
Create Date: 2024-01-17 21:34:44.228554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '729af6d55beb'
down_revision = '359cd5385dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vuelto', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoEfectivo', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoVisa', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoBBVA', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoBCP', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoYape', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('total_venta',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('acuenta',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('deuda',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.alter_column('deuda',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('acuenta',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_venta',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('pagoYape')
        batch_op.drop_column('pagoBCP')
        batch_op.drop_column('pagoBBVA')
        batch_op.drop_column('pagoVisa')
        batch_op.drop_column('pagoEfectivo')
        batch_op.drop_column('vuelto')

    # ### end Alembic commands ###
