"""agregando detalle caja columnas de pago

Revision ID: 770544c30137
Revises: d49a5634ae8c
Create Date: 2024-02-21 15:07:46.383099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '770544c30137'
down_revision = 'd49a5634ae8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagoEfectivo', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoVisa', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoBBVA', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoBCP', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagoYape', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('monto')
        batch_op.drop_column('nota_dinero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_dinero', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('monto', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('pagoYape')
        batch_op.drop_column('pagoBCP')
        batch_op.drop_column('pagoBBVA')
        batch_op.drop_column('pagoVisa')
        batch_op.drop_column('pagoEfectivo')

    # ### end Alembic commands ###
