"""add two columns note

Revision ID: 8a26fa363c3a
Revises: 
Create Date: 2023-01-29 22:17:07.540762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a26fa363c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acuenta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deuda', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.drop_column('deuda')
        batch_op.drop_column('acuenta')

    # ### end Alembic commands ###
