"""Agregando cols bools en nota de pedido

Revision ID: b44bbbaa20ed
Revises: 778c4808c01f
Create Date: 2024-02-10 17:49:11.386238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bbbaa20ed'
down_revision = '778c4808c01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bool_acuenta', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bool_deuda', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.drop_column('bool_deuda')
        batch_op.drop_column('bool_acuenta')

    # ### end Alembic commands ###
