"""agregando columna precio_ferreteria_producto

Revision ID: ee303f8796f5
Revises: cd0ba78dcbce
Create Date: 2024-02-23 20:26:38.019648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee303f8796f5'
down_revision = 'cd0ba78dcbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
