"""agregando usuario_id NotaPedido

Revision ID: ef7b050fb2c7
Revises: ffa64a1c5bfa
Create Date: 2024-02-23 10:23:10.848721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7b050fb2c7'
down_revision = 'ffa64a1c5bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
