"""Add_nota_tel_dni

Revision ID: fd3465e69c34
Revises: 
Create Date: 2023-01-02 20:36:04.158355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3465e69c34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_comprador', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dni_comprador', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notapedido', schema=None) as batch_op:
        batch_op.drop_column('dni_comprador')
        batch_op.drop_column('numero_comprador')

    # ### end Alembic commands ###
